### ISSUE TITLE
create header - client

### ISSUE THREAD

**Issue by Vuologist** [Vuologist/bumpie#1]
![image](https://user-images.githubusercontent.com/15658088/77984986-fe603e00-72c7-11ea-95f3-b62dd124e531.png)

please create a header component for the client side

- image was pulled from user settings
- assets can be found in google drive

specifics
- add color change animation onhover on icon so users know it can be clicked
- add color change animation onhover over: notifications settings, user setting, log out
- for now: notifications settings, user setting, log out functionality will be none
- bumpie logo: functionality: none
- DASHBOARD: functionality: none

**Comment by Vuologist** [comment]
Heather's Task:
- animations and onhover

Anthony's Task:
- create routing and basic layout

**Comment by choum** [comment]
TODOS Sprint 2

- Dropdown Menu on Hover
- Add SVG in replacement of images
- Shift those things out more
![image](https://user-images.githubusercontent.com/10792485/79050522-69224b00-7bdf-11ea-8756-cdef172cb459.png)

**Comment by Vuologist** [comment]
Closing issue because new issues were created to deal with sub parts
