### ISSUE TITLE
Design - Create confirmation pages for sign up and password reset (1)

### ISSUE THREAD

**Issue by peggyzhouu** [Vuologist/bumpie#118]
DoD: (1) Use the trailed airplane illustration for sign up confirmation page to let the user know an email verification has been sent to their inbox. Use folder and airplane illustration for password reset page. (2) ping @Vuologist when finished

**Comment by Vuologist** [comment]
1. can you move the email verification artboard next to the sign-up artboards
2. can you group the forgot password artboards together?
3. can we move the hex design artboards somewhere else or delete after versioning the stuff?
