### ISSUE TITLE
Overseer - There _has_ to be a better way

### ISSUE THREAD

**Issue by RyanSW** [Vuologist/bumpie#132]
https://github.com/Vuologist/bumpie/blob/aa0b847f9f5372ba9393f916435c204c0da117e2/client-react/src/dashboard/CategoryBox.js#L83
https://github.com/Vuologist/bumpie/blob/aa0b847f9f5372ba9393f916435c204c0da117e2/client-react/src/dashboard/CategoryBox.js#L128

These functions displease your supreme overseer. Explain yourself @Vuologist .

**Comment by Vuologist** [comment]
my supreme overseer, this is the best your underlings can perform at the moment. would you grace us with your unending knowledge and enlighten us to a better methodology?
