### ISSUE TITLE
Shift ends of header further out

### ISSUE THREAD

**Issue by Vuologist** [Vuologist/bumpie#15]
![image](https://user-images.githubusercontent.com/15658088/78631568-9672a000-7851-11ea-9fc0-e12bd6984cfc.png)

I think it would look nicer and adhere closer to the XD markup, if we shift those things out more

**Comment by Vuologist** [comment]
approved. need to also decrease height of header.

can also possible resolve #12

**Comment by choum** [comment]
covered in #1
