### ISSUE TITLE
Create: Notify me through... - client

### ISSUE THREAD

**Issue by Vuologist** [Vuologist/bumpie#3]
![image](https://user-images.githubusercontent.com/15658088/77986549-3a959d80-72cc-11ea-9830-ddd21b7e1878.png)

XD page - Settings

Notification Settings
- create a component for a switch button
   - create animation for smooth switching

**Comment by Vuologist** [comment]
make the notify my through and hr a component.

have everything inside notification settings one div

**Comment by choum** [comment]
TODO Spring 2

- Responsive? (not sure anthony needs to address later)
