### ISSUE TITLE
Create: Notify me... - client

### ISSUE THREAD

**Issue by Vuologist** [Vuologist/bumpie#4]
![image](https://user-images.githubusercontent.com/15658088/77987487-c7415b00-72ce-11ea-86d4-61ad0f55f18e.png)

XD page - Settings

Notification Settings

- create a component for a horizontal radio button
   - create animation for smooth switching

**Comment by choum** [comment]
TODOS Sprint 2

- Functionality of the Radio Buttons (maybe meet up with anthony to discuss)?
